Dockerfile
=> chore: remove obsolete deps

Dockerfile
=> feat(deps): update java to v11

Dockerfile
https://github.com/renovatebot/renovate/pull/6434
=> feat: install lerna globally

Dockerfile
Needs https://github.com/renovatebot/docker-buildpack/issues/53
=> feat: add dotnet

Dockerfile
=> chore: fix dotnet datasource

Dockerfile, renovate.json
This adds helm to the renovate full image as per https://github.com/renovatebot/docker-renovate-full/issues/139
---
closes #139
=> Added helm to renovate Docker image

Dockerfile
ref renovatebot/docker-buildpack#156
=> chore: update renovate sources

Dockerfile
ref containerbase/buildpack#14
=> feat: update php installer

.github/workflows/build.yml, .github/workflows/cron.yml
See https://github.com/renovatebot/internal-tools/pull/261
=> ci: install sigstore

.github/workflows/build.yml, .github/workflows/cron.yml
See https://github.com/renovatebot/docker-renovate/pull/244
Fixes #393
=> fix: explicitly set required GITHUB_TOKEN permissions

Dockerfile
Discussed in [renovatebot/renovate#13569](https://github.com/renovatebot/renovate/discussions/13569)
=> feat: Add jsonnet-bundler

Dockerfile, bin/docker-entrypoint.sh
Use hardcoded node version for renovate executables
=> feat: pin node for renovate

renovate.json
We've no lockfiles in this repo.
- https://github.com/renovatebot/renovate/issues/18543
=> chore: disable lockfile maintenance

Dockerfile
I missed to update this image to new containerbase image
- closes #1108
=> fix: use newer base image

builder.json
merge after v35 and before other major updates
=> build: only rebuild v35

.github/workflows/build.yml, .github/workflows/trivy.yml, README.md
- closes https://github.com/renovatebot/docker-renovate/issues/1237
=> feat!: publish as full tag

Dockerfile
=> feat!: use global mode

.github/workflows/build.yml, builder.json
create multi arch images
- renovatebot/renovate#9229
=> feat: build arm64 / aarch64

.github/workflows/build.yml, renovate.json
=> ci: allow merge queue

Dockerfile
@viceice added bun to containerbase/base by https://github.com/containerbase/base/pull/1441 but it was never added to renovate-full.
Tested very simply, only ran `docker build -t test . && docker run --entrypoint bun test` and seems to work, let me know if there's anywhere I need to add tests or anything I'm missing, apologies if so.
=> feat: add bun

Dockerfile
This needs https://github.com/containerbase/base/pull/1737 to land first.
=> feat: add bazelisk
